Release v0.2
dantecatalfamo/himalaya-emacs pull request #16
Opened 2022-12-21 10:11 UTC by soywod

I just prepared the code for the next release [v0.6.2](https://github.com/soywod/himalaya/pull/433) and bumped the version of the plugin. Develop can be merged whenever the release is out.

Tiny question @dantecatalfamo about MELPA, what is the process for publishing new versions?

2022-12-21 17:49 UTC, dantecatalfamo commented
All you have to do is push code to master, MELPA automatically looks for changes and rebuilds the package every hour 🙂

2022-12-21 17:52 UTC, soywod commented
> All you have to do is push code to master, MELPA automatically looks
> for changes and rebuilds the package every hour 🙂

This is awesome!

2022-12-29 00:40 UTC, dantecatalfamo requested changes
We'll need the Commentary section added back

2022-12-29 00:43 UTC, dantecatalfamo commented
Okay I re-added it, should be good now!

2022-12-29 00:43 UTC, dantecatalfamo approved these changes

2022-12-29 11:14 UTC, soywod commented on himalaya.el
> -;;; Commentary:
Sorry, my bad!

2022-12-29 11:15 UTC, soywod commented
> Okay I re-added it, should be good now!

Thank you @dantecatalfamo!

I just push a nice feature https://github.com/dantecatalfamo/himalaya-emacs/pull/17, feel free to review / change directly on the branch.

2023-01-09 22:41 UTC, merged

2023-01-09 22:42 UTC, dantecatalfamo commented
Sorry that took so long, I assumed you would merge the branch after I approved it :slightly_smiling_face:

2023-01-10 06:00 UTC, soywod commented
Oups, in fact I was waiting for the release [v0.6.2](https://github.com/soywod/himalaya/pull/433) to be out (hence the `[Pending]`). So it means a new version has been automatically deployed on MELPA? I guess it will be broken the time for the release to be available :smile:

2023-01-10 14:31 UTC, dantecatalfamo commented
Oh, I thought it was pending my merge :grimacing: